name: Ktlint Check

on:
  pull_request:
    branches:
      - master

jobs:
  ktlint:
    name: Run Ktlint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Run Ktlint Check
        run: ./gradlew ktlintCheck
